### ISSUE TITLE
Signing server for Dropper

### ISSUE THREAD

**Issue by oolumorin** [moonstream-to/waggle#24]
# Goal
To add server functionality in `waggle` that enables admins to sign drops. 

# Requirement
See [design documentation](https://docs.google.com/document/d/1iGBSkZcw4D4yrTiX4KGKx9xsHiH0CHiL8If4IzzXWrw/edit#heading=h.9hvsaet1xcoo)

# Milestones

- [x] Set up server
- [ ] Test internally - Dec 13
- [ ] Send documentation - Dec 14
- [ ] Demo with CG

**Comment by kompotkot** [comment]
Resolves PR https://github.com/moonstream-to/waggle/pull/23
